service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: backend-service-1-sgkuoe49xg
  name: backend-service-1-sgkuoe49xg
  selector: backend-service-1-sgkuoe49xg
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-backend-service-1-sgkuoe49xg
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-1-sgkuoe49xg
    type: springboot
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: backend-service-1-sgkuoe49xg
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: backend-service-1-sgkuoe49xg
    port: 8080
  volume:
    name: pvc-backend-service-1-sgkuoe49xg
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
    redis:
      name: secret-redis-standalone-1-p4tlo8hhvw
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-1-sgkuoe49xg
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
