service:
  port:
    name: http
    l4_protocol: TCP
    port: 8080
    targetPort: 8080
  label: backend-service-1-sgkuoe49xg
  name: backend-service-1-sgkuoe49xg
  selector: backend-service-1-sgkuoe49xg
  type:
  - ClusterIP
  - NodePort
namespace: sssss-dev
pvc:
  name: pvc-backend-service-1-sgkuoe49xg
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: backend-service-1-sgkuoe49xg
    type: springboot
  replicas: 1
  update:
    type: RollingUpdate
  repo:
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
  image:
    name: backend-service-1-sgkuoe49xg
    tag: lastest
    secret: regsecret
  container:
    name: backend-service-1-sgkuoe49xg
    port: 8080
  volume:
    name: pvc-backend-service-1-sgkuoe49xg
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  backing: 
    redis:
      name: secret-redis-standalone-1-p4tlo8hhvw
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-backend-service-1-sgkuoe49xg
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
